name: noise2inverse
channels:
- conda-forge
- astra-toolbox
dependencies:
- python=3.10
- pip
- ipython
- ipykernel
# pytorch (GPU build from conda-forge)
- pytorch-gpu
# plotting and utilities
- scikit-image
- matplotlib
- seaborn
- tifffile
- tqdm
# Tomography
- foam_ct_phantom
- tomopy
- astra-toolbox
- pip:
  - git+https://github.com/ahendriksen/tomosipo.git
  - bm3d
